### ISSUE TITLE
x11-over-vsock.exe crashing...

### ISSUE THREAD

**Issue by pmorch** [nbdd0121/x11-over-vsock#2]
I love the concept. Great that my X11 clients don't die when the network changes.

However, I've now seen `x11-over-vsock.exe --daemon` crash a number of times - about once a day. Often when I close the lid of the laptop, go somewhere and re-open the laptop, then I can see in Task Manager that `x11-over-vsock.exe` is no longer running, and all my X11 clients have disappeared. (Which is ironic, because that is exactly the use-case I want to solve... :-))

It doesn't happen consistently enough that I can reproduce it reliably, unfortunately. Of course I'll keep trying to figure out how to reproduce it. But I'm not sure what else to do. Is there anything I can do to do debug the situation? Any log files to investigate, any crash core files I can send you? Anybody else seeing this?

**Comment by nbdd0121** [comment]
Can you run x11-over-vsock in cmd to see if there are any errors?

**Comment by pmorch** [comment]
Ok, I'll run it in a `cmd.exe` window for the time being and report back if anything gets printed there when/if it crashes next time. I just took the laptop out of the bag after the café yesterday, and my clients are still running, so no crash this time...

Oh, and you might already have made the connection, but my setup is as documented in #1.

**Comment by nbdd0121** [comment]
Could it be a misconfiguration in task scheduler? Make sure you didn't check "Start the task only if the computer is on AC power", "Stop if the computer switches to battery power" in conditions, and "Stop the task if it runs longer than" in settings (these are on by default).

**Comment by pmorch** [comment]
I think you're probably absolutely right. I'm apologize for the noise. I'll let it run the next couple of days and then update #1 accordingly.
